language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.8.0"
  - DJANGO="django==1.7.4"
  - DJANGO="django==1.6.10"
  - DJANGO="django==1.5.12"
  - DJANGO="django==1.4.19"

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django==1.4.19"
    - python: "3.4"
      env: DJANGO="django==1.4.19"

install:
  - pip install $DJANGO --use-mirrors
  - pip install jinja2 --use-mirrors
  - pip install pytz --use-mirrors

script:
  - setup.py test
