language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.8.0"
  - DJANGO="django==1.7.4"
  - DJANGO="django==1.6.10"

install:
  - pip install $DJANGO --use-mirrors
  - pip install django-jinja --use-mirrors

script:
  - cd testing && python manage.py test
