language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="django==1.8.6"
  - DJANGO="django==1.7.10"

install:
  - pip install $DJANGO --use-mirrors
  - pip install django-jinja==1.4.1 --use-mirrors

script:
  - cd testing && python manage.py test
