name: Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Tests
        run: make test

      - name: Upload coverage to Codecov
          run: bash <(curl -s https://codecov.io/bash)
